name: Build Docs
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unix:
    runs-on: ubuntu-latest
     
    strategy:
      fail-fast: false


    steps:
      - uses: actions/checkout@v2

      - name: Install apt-get dependencies
        run: |
          sudo apt-get install -y ffmpeg python make build-essential python3-pip --yes

      - name: Install b2d via pip
        run: |
          python -m pip install .

      - name: Install pip doc dependencies
        run: |
          python -m pip install -r docs/requirements.txt

      - name: Build the docs
        run: |
          cd docs
          build html